### ISSUE TITLE
Problem with Darius-cnn-ip

### ISSUE THREAD

**Issue by SilverPoker** [Xilinx/PYNQ-DL#1]
I download this whole project with  to my pynq board and change the overlay path to the right place. When I run the first time, the data printed is the same as  darius-cnn-ip.ipynb, so it's loaded right . However, when I explore the detailed  parameter, I find many problems.
First, when I print the OFM array, I find many negative number in it??? The input IFM and weight is the same as the demo which is random ranging from 0 to 255. I can't explain why the convolution and max pooling can change positive integer to negtive integer.......
Then, I change the parameter for pooling and run the demo again, I find the OFM does't change. I can't explain why this happens. 

You can also find the first problem, just by changing your demo in  darius-cnn-ip.ipynb:
`for i in range(0, 15, 4):
    print(hex(ofm[i]))`
change to a larger range:
`for i in range(0, 159, 4):
    print(hex(ofm[i]))`
and many problems.

You can try different pooling parameter and see if the output OFM is changed.
 
If my operation is wrong, can you show me the right using process?

**Comment by rpokana** [comment]
Hi,

Thanks for trying out Darius notebook and getting back to us on your concerns.

Firstly, let me clarify some assumptions. Any 16 bit signed integers are acceptable for IFM and weight values to support all kinds of image formats or intermediate layers. 

And to answer your questions:
1. The convoluted output can also be negative as it is also declared as signed int16. So, it can range from -32,768 to 32, 767. Even if 2 positive integers have been convoluted, the result can be out of bounds of 15 bits and can be represented as negative integer with 16th bit as sign bit. The maxpooled output can be a negative integer for cases where the maxpool window of convoluted output has all negative integers and maximum could again be negative.

2. Can you provide the testcase with different pool parameters for which you are getting the same ofm? I have tried different pool dimensions and each time I got different OFM values. 

Also we would like to understand if the overlay you are using is different from the overlay provided. Because, if it is same one, you don’t have to change the path.

Thanks
Radhika

**Comment by rpokana** [comment]
Hi,

Since there was no response for a week, closing the issue. I am assuming things have been clarified. If there is still an issue, please raise a new one.

Thanks
Radhika
